title: Run production-grade databases easily on Kubernetes
baseurl: https://kubedb.com
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  product_key: kubedb
  main_menu_dropdown_item: database
  domain_appscode: https://appscode.com
  domain_voyagermesh: https://voyagermesh.com
  domain_stash: https://stash.run
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeform: https://kubeform.com
  domain_pharmer: https://pharmer.cloud
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_engine_ID: 015199383701854252104:8mvwy0fek2e
  search_api_key: AIzaSyBo15AW3hatf4fO8actJUZ_d5qZJpx0rXM
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
menu:
  main:
  - name: Databases
    identifier: database
    weight: 15
    url: https://kubedb.com/docs/latest/setup/
  - name: Documentation
    weight: 20
  - name: Community
    identifier: community
    weight: 25
  - name: Elasticsearch
    identifier: elasticsearch
    parent: database
    weight: 10
  - name: MariaDB
    identifier: mariadb
    parent: database
    weight: 20
  - name: Memcached
    identifier: memcached
    parent: database
    weight: 30
  - name: MongoDB
    identifier: mongodb
    parent: database
    weight: 40
  - name: MySQL
    identifier: mysql
    parent: database
    weight: 50
  - name: Percona XtraDB
    identifier: percona-xtradb
    parent: database
    weight: 60
  - name: PgBouncer
    identifier: pgbouncer
    parent: database
    weight: 70
  - name: PostgreSQL
    identifier: postgres
    parent: database
    weight: 80
  - name: ProxySQL
    identifier: proxysql
    parent: database
    weight: 90
  - name: Redis
    identifier: redis
    parent: database
    weight: 100
  - name: GitHub
    identifier: github
    parent: community
    url: https://github.com/kubedb
    weight: 1
  - name: Twitter
    identifier: twitter
    parent: community
    url: https://twitter.com/KubeDB
    weight: 2
  - name: Slack
    identifier: slack
    parent: community
    url: http://slack.kubernetes.io/
    weight: 3
markup:
  goldmark:
    renderer:
      unsafe: true
